# Generated by Django 3.2.3 on 2021-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoecormeceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='product_views', to='Djangoecormeceapp.IpAdress'),
        ),
    ]
